### PR TITLE
Lock ruby version to 2.2.0

### PR DESCRIPTION
**Pull request by amsardesai**
This is so that everyone, including travis CI, defaults to Ruby 2.2.0 on their systems when working on this project. The `.ruby-version` file works with most ruby version managers. It would ensure consistency when doing anything in ruby.

Also added myself to the contributors list :smiley:

### CODE REVIEW

**Comment by JGulbronson** [comment]
@amsardesai The build seems to be failing on Travis. Can you take a look?

**Comment by amsardesai** [comment]
Merged #226 into this

**Comment by JGulbronson** [comment]
Sweet, looks like the builds are passing now. We don't do much in Ruby, but it's not a bad idea to lock in the version in case people experience issues. Question about the specific version you chose: A lot of the gems we're using are fairly old, will using 2.x instead of 1.x break anything? (if so, we can likely fix it by bumping the gem version)

**Comment by amsardesai** [comment]
The version I picked was the latest stable version of ruby, and there really isn't anything significantly different from 1.9.3, at least in comparison to 1.8.7 vs 1.9.3, which had a lot of changes. I think better to start off with the latest version.

**Comment by JGulbronson** [comment]
I'm pretty sure having bundle in `Gemfile.lock` but not `Gemfile` will cause some issues, since it's currently listed as a dependency. @jlfwong can you chime in on this?

**Comment by amsardesai** [comment]
I don't think there is a `Gemfile.lock` in the repo. If you run `bundle install` it will update the `Gemfile.lock` with the correct dependencies.

**Comment by JGulbronson** [comment]
Hey @amsardesai can you list the steps you used to test locally?

**Comment by JGulbronson** [comment]
Inactive, will reopen if there's interest

**Pull request closed without merging**
