### PR TITLE
Prevent PhantomJS requests to Google Analytics

### LINKED ISSUE #150: Filter out phantomjs requests from analytics stats
Recently, we added a weekly cronjob to have phantom.js to create snapshots of our dynamic course pages (so they can be indexed by search engine spiders). See https://github.com/UWFlow/rmc/commit/2c675ece2d02efdae97bd736a5ce773b045ee373.

However, for phantom.js to create the snapshots for the course pages, it has to make a request to each course page. This screws up our analytic stats on Mixpanel and Google Analytics. For example, the spikes in the # of visitors per day graph (Google Analytics) below are caused by phantom.js:

image

So we need to either find a way to either filter out phantom.js from Mixpanel and Google Analytics stats or find a way to generate the snapshots without generating requests to the production site.

### PR DESCRIPTION
**Pull request by JGulbronson**
@mduan can you give this a quick look? I don't think I'll be able to get it merged for today's index, but definitely for next weeks.

Fixes #150

### CODE REVIEW

**Comment by JGulbronson** [comment]
Going to merge so I can deploy in time for this week's index.

**Comment by jlfwong** [comment]
Oh cool - clever fix

**Comment by JGulbronson** [comment]
Yeah, it looks like it'll work. I'll post an update after the index on Wednesday, to see if it stops the analytics from being *way* higher.

**Comment by mduan** [comment]
Sorry I didn't get a chance to look at this earlier, but this looks great. Nice fix.

**Comment by JGulbronson** [comment]
Looks like it worked! (That last dot is yesterday)
screen shot 2015-06-11 at 1 50 33 pm

**Comment by divad12** [comment]
Thanks for the fix!

**Pull request merged**
